name: Run My Playwright Tests

on:
  schedule:
    - cron: '10 6 * * *'  # Каждый день в 06:10 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install --with-deps chromium firefox
    - name: -= RUN MY TESTS HERE =-
      run: |
        pytest ./tests2/test_inet_tester_3.py -v --tb=short
